#!/bin/bash
# One-shot registration of ALL PEAM analyses into a TraceCompass workspace —
# replaces clicking through "Add External Analysis..." and "Manage XML
# analyses... > Import" one by one.
#
#   usage: ./tc-setup.sh            (uses TC_WORKSPACE from config/defaults)
#
# RUN WITH TRACECOMPASS CLOSED: TC reads these locations at startup and
# caches state; changes made while it runs may be ignored or overwritten.
#
# What it installs (paths confirmed against TC source, LamiConfigUtils.java
# and XmlUtils.java):
#   1. External (LAMI) analyses — one .properties file (keys: name, command)
#      per analysis under
#      .metadata/.plugins/org.eclipse.tracecompass.analysis.lami.core/user-defined-configs/
#      pointing at the committed lami_<analysis>.sh wrappers in this folder.
#   2. XML data-driven analyses — copies src/tracecompass/*.xml into
#      .metadata/.plugins/org.eclipse.tracecompass.tmf.analysis.xml.core/xml_files/
#
# Idempotent: existing PEAM entries/files are overwritten with current ones.

. "$(dirname "$0")/tc-common.sh" 2>/dev/null || {
  # tc-common.sh ends by defining functions only; sourcing must not exec.
  echo "error: cannot source tc-common.sh" >&2; exit 1
}

WS="${TC_WORKSPACE}"
if [ ! -d "$WS/.metadata" ]; then
  echo "error: '$WS' does not look like an Eclipse workspace (no .metadata)." >&2
  echo "Set TC_WORKSPACE in tc-local.conf (see tc-local.conf.example)." >&2
  exit 1
fi

LAMI_DIR="$WS/.metadata/.plugins/org.eclipse.tracecompass.analysis.lami.core/user-defined-configs"
XML_DIR="$WS/.metadata/.plugins/org.eclipse.tracecompass.tmf.analysis.xml.core/xml_files"
mkdir -p "$LAMI_DIR" "$XML_DIR"

# ---- 1. external (LAMI) analyses -----------------------------------------
register() {  # register <analysis_module> <display name>
  local mod="$1" disp="$2"
  local wrapper="$TC_HERE/lami_${mod}.sh"
  if [ ! -x "$wrapper" ]; then
    echo "skip: $wrapper not found/executable" >&2; return
  fi
  local f="$LAMI_DIR/pinsight_${mod}.properties"
  {
    echo "# PEAM external analysis (generated by tc-setup.sh; safe to delete)"
    echo "name=$disp"
    echo "command=$wrapper"
  } > "$f"
  echo "registered external analysis: $disp"
}

register load_imbalance   "PInsight load imbalance"
register mpi_latency      "PInsight MPI latency"
register gpu_datamovement "PInsight GPU data movement"
register halo_exchange    "PInsight halo exchange"

# ---- 2. XML data-driven analyses -----------------------------------------
XML_SRC="$(cd "$TC_HERE/../../tracecompass" 2>/dev/null && pwd)"
if [ -n "$XML_SRC" ] && [ -d "$XML_SRC" ]; then
  for x in "$XML_SRC"/*.xml; do
    [ -f "$x" ] || continue
    cp "$x" "$XML_DIR/"
    echo "installed XML analysis: $(basename "$x")"
  done
else
  echo "skip: XML source folder not found (expected src/tracecompass next to src/python)" >&2
fi

echo
echo "Done. Start TraceCompass; the analyses appear under External Analyses"
echo "and apply to traces automatically (XML). Workspace: $WS"
